version: '3.5'

services:

  app:   
    build:
      context: .
      dockerfile: Dockerfile
      platforms: 
        - "linux/amd64"
    env_file:
      - .env
    volumes:
      # - "./logs:/go/app/logs" 
      - "./repositories:/go/app/repositories" 
    ports:
      - "8082:8082"